#!/bin/bash
#----------------------------------------------------------
# diako.cafe - internet cafe software
# (c) 2017 Jens Kallup
# all rights reserved!
#----------------------------------------------------------

export TERM="linux-c"	# default, Linux colored console
export PATH=$PATH:/bin:/sbin:/usr/local/bin:/usr/bin:/usr/sbin
export LD_LIBRARY_PATH=/usr/local/lib:/lib:/lib64:/lib/X11:/lib64/plugins

echo "Loading, please wait..."

#---------------------------------------------------
# check if we on production system, if so - exit ...
#---------------------------------------------------
if [ -e "/secure" ]; then
echo "You sit on a production-system."
echo "All BootUp will be stop!"
exit 1
fi

[ -d /dev  ] || mkdir -m 0755 /dev
[ -d /sys  ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp  ] || mkdir /tmp

#mknod -m 622 /dev/console c 5 1
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0
mknod -m 444 /dev/urandom c 1 9

mknod -m 660 /dev/mem c 1 1

mkdir /dev/pts
mkdir /dev/shm

mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

mkdir -p /var/lock
mkdir -p /var/log

mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc

#----------------------------------------------------------------
# create required /dev nodes entries for user command console ...
#----------------------------------------------------------------
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 444 /dev/random c 1 8

/sbin/getty -l sh -n 38400 tty0
/sbin/getty -l sh -n 38400 tty1

modprobe e1000
ifconfig lo   up 127.0.0.1
ifconfig eth0 up 192.168.188.20
route add default gw 192.168.100.1 eth0

mknod -m 666 /dev/fb0 c 29 0
export FRAMEBUFFER=/dev/fb0

#-----------------------------------------
# do'ing ramdisk security login things ...
#-----------------------------------------
cat > /etc/passwd << "EOF"
root:x:0:0:root:/root:/bin/bash
EOF

cat > /etc/group << "EOF"
root:x:0:
bin:x:1:
sys:x:2:
tty:x:4:root
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
EOF

#-----------------------------------------------------
# now, load default keymap,
# and set german extra keys like the EuroSign etc. ...
#-----------------------------------------------------
loadkeys /etc/key.map2.gz

echo "nameserver 8.8.8.8" > /etc/resolv.conf

/bin/bash
# here we are exit our domain - reboot...
#########################################
## E O F
########
